"""Shared T-SQL highlighting helpers used by the SQL editor."""

from PySide6.QtGui import QColor, QFont, QTextCharFormat

from app.ui.theme import Theme

TSQL_KEYWORDS = {
    "SELECT",
    "INSERT",
    "UPDATE",
    "DELETE",
    "MERGE",
    "VALUES",
    "INTO",
    "OUTPUT",
    "RETURNING",
    "CREATE",
    "DROP",
    "ALTER",
    "TRUNCATE",
    "TABLE",
    "VIEW",
    "INDEX",
    "PROCEDURE",
    "FUNCTION",
    "TRIGGER",
    "DATABASE",
    "SCHEMA",
    "FROM",
    "WHERE",
    "GROUP",
    "HAVING",
    "ORDER",
    "BY",
    "LIMIT",
    "OFFSET",
    "TOP",
    "DISTINCT",
    "ALL",
    "UNION",
    "INTERSECT",
    "EXCEPT",
    "WITH",
    "JOIN",
    "INNER",
    "LEFT",
    "RIGHT",
    "FULL",
    "OUTER",
    "CROSS",
    "ON",
    "USING",
    "AS",
    "ASC",
    "DESC",
    "AND",
    "OR",
    "NOT",
    "IN",
    "EXISTS",
    "BETWEEN",
    "LIKE",
    "IS",
    "NULL",
    "TRUE",
    "FALSE",
    "ANY",
    "SOME",
    "CASE",
    "WHEN",
    "THEN",
    "ELSE",
    "END",
    "IF",
    "BEGIN",
    "WHILE",
    "RETURN",
    "DECLARE",
    "SET",
    "PRINT",
    "EXEC",
    "EXECUTE",
    "GO",
    "PRIMARY",
    "FOREIGN",
    "KEY",
    "REFERENCES",
    "DEFAULT",
    "CHECK",
    "UNIQUE",
    "CONSTRAINT",
    "IDENTITY",
    "CASCADE",
}

TSQL_FUNCTIONS = {
    "COUNT",
    "SUM",
    "AVG",
    "MIN",
    "MAX",
    "COALESCE",
    "ISNULL",
    "NULLIF",
    "CAST",
    "CONVERT",
    "TRY_CAST",
    "TRY_CONVERT",
    "FORMAT",
    "LEN",
    "LEFT",
    "RIGHT",
    "SUBSTRING",
    "REPLACE",
    "TRIM",
    "LTRIM",
    "RTRIM",
    "UPPER",
    "LOWER",
    "CONCAT",
    "CHAR",
    "ASCII",
    "GETDATE",
    "SYSDATETIME",
    "DATEADD",
    "DATEDIFF",
    "DATEPART",
    "YEAR",
    "MONTH",
    "DAY",
    "ROW_NUMBER",
    "RANK",
    "DENSE_RANK",
    "PARTITION",
    "OVER",
    "ABS",
    "ROUND",
    "FLOOR",
    "CEILING",
    "POWER",
    "SQRT",
}


def make_format(color: str, *, bold: bool = False, italic: bool = False) -> QTextCharFormat:
    fmt = QTextCharFormat()
    fmt.setForeground(QColor(color))
    if bold:
        fmt.setFontWeight(QFont.Weight.Bold)
    if italic:
        fmt.setFontItalic(True)
    return fmt
